### ISSUE TITLE
Readme instructions are for synchronous code, but module appears to be acync

### ISSUE THREAD

**Issue by jcreager** [brendanashworth/generate-password#17]
Hi @brendanashworth 

I hope this isn't a silly question.  I am wondering if I am missing something in the readme for this module?  It looks like the example code is synchronous:

~~~javascript
var generator = require('generate-password');
 
var password = generator.generate({
    length: 10,
    numbers: true
});
 
// 'uEyMTw32v9' 
console.log(password);
~~~

However, console.log in this example returns undefined rather than the password.  If I modify the code by passing a callback function as follows:

~~~javascript
var generator = require('generate-password');
 
var password = generator.generate({
    length: 10,
    numbers: true
}, function (err, password) {
    console.log(password) //logs password to console
});
~~~

The password is logged to the console as expected rather than undefined.

I dug a little deeper and it looks like the self.generate method actually does return a callback:

~~~javascript
	var password = generate(options, pool); //assign callback to var password

	return password; // return callback
~~~

That said, I do not see any open issues for your library pertaining to the issue that I have encountered.  I am hoping to verify with you if I am missing something else, or if I am on the right track with this being an async module?

Thank you,
Joe

**Comment by brendanashworth** [comment]
Hi @jcreager, apologies for the response time.

The module is entirely synchronous and doesn't offer an asynchronous option. One could be added in the future but as of right now, [we only use sync methods](https://github.com/brendanashworth/generate-password/blob/23642b080e5bb25af936439266aad7b4c714cc4f/src/generate.js#L8) and don't use any callbacks.

Sorry if that's confusing. I'll try and fix your confusion:

> console.log in this example returns undefined

It will return undefined — it'll print the password to the console. `password` is where the value is.

> The password is logged to the console as expected rather than undefined.

The module code doesn't support any async stuff, so that shouldn't — and doesn't — work. [The function](https://github.com/brendanashworth/generate-password/blob/23642b080e5bb25af936439266aad7b4c714cc4f/src/generate.js#L55) doesn't even accept a callback parameter.

> self.generate method actually does return a callback

It does not. The inner `generate` will always return a string.

Did that clear it all up?
