### ISSUE TITLE
Setting numbers to true in options does not guarantee number used

### ISSUE THREAD

**Issue by dallen4** [brendanashworth/generate-password#36]
# Details
I'm not sure if the boolean values were intended to _always_ include that character type or only most of the time, but I used this library to aid in a temporary password flow and had a number of instances where providing the following options resulted in a password string _without_ a number.

```
{
    length: 15,
    lowercase: true,
    uppercase: true,
    symbols: true,
    numbers: true,
    exclude: '+=',
}
```

I tried this with multiple other options configurations and found that passing a `numbers` value of `true` does _not_ in fact guarantee that the generated string will include a numeric value.

**Comment by mt-sebastien-robert** [comment]
Those are ignore if you don't use the `strict` option.

**Comment by brendanashworth** [comment]
@dallen4 it's true that the `strict` option is needed to ensure those characters are included in the password. While it may be less intuitive, having that as the default results in passwords with slightly more entropy = strength. Perhaps that should be better documented (PRs are welcome!), but I'm going to close this issue otherwise. 🍾
