### ISSUE TITLE
[bug] Password generation with numbers

### ISSUE THREAD

**Issue by carlosfanti** [brendanashworth/generate-password#47]
Similar to the #46, when using the param **numbers:true**, the generation no always result on a password with number.

You can see the behavior on the code test bellow
https://runkit.com/carlosfanti/generate-password-bug-numbers-true

![image](https://user-images.githubusercontent.com/8270067/85128409-843db680-b231-11ea-8247-faebf5d87bcc.png)

**Comment by carlosfanti** [comment]
If I use **strict:true**, it works well:

![image](https://user-images.githubusercontent.com/8270067/85129643-bcde8f80-b233-11ea-8e97-bdc89f831e08.png)

**Comment by DillonStreator** [comment]
@carlosfanti This is not a bug. It's by design.
Setting `numbers:true` does not guarantee you a number. It just means that numbers will be apart of a pool of characters that could be drawn from. It does not guarantee that you will get a number.
This is the reason for the `strict` param. `strict` guarantees that your output contains one character from each set.

**Comment by carlosfanti** [comment]
@DillonStreator Thank you for the explanation!

**Comment by francofantini** [comment]
OMHO strict should default to true.
